services:
  - type: worker
    name: vebtc-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 telegram_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GITHUB_DATA_URL
        sync: false
